name       : haskell-StateVar
version    : 1.1.0.4
release    : 1
source     :
    - http://hackage.haskell.org/package/StateVar-1.1.0.4/StateVar-1.1.0.4.tar.gz : 7ad68decb5c9a76f83c95ece5fa13d1b053e4fb1079bd2d3538f6b05014dffb7
license    : BSD-3-Clause
component  : programming
summary    : This package contains state variables, which are references in the IO monad, like IORefs or parts of the OpenGL state. 
description: |
    This package contains state variables, which are references in the IO monad, like IORefs or parts of the OpenGL state. 
builddeps  :
    - ghc
    - haskell-stm
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 StateVar-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/StateVar-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/StateVar-$version/*.a
