name       : haskell-StateVar
version    : 1.1.0.4
release    : 3
source     :
    - http://hackage.haskell.org/package/StateVar-1.1.0.4/StateVar-1.1.0.4.tar.gz : 7ad68decb5c9a76f83c95ece5fa13d1b053e4fb1079bd2d3538f6b05014dffb7
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains state variables, which are references in the IO
    monad, like IORefs or parts of the OpenGL state.
description: "This package contains state variables, which are references in the IO\
    \ monad, like IORefs or parts of the OpenGL state. \n"
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-stm
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
