name       : haskell-StateVar
version    : 1.1.1.0
release    : 4
source     :
    - https://hackage.haskell.org/package/StateVar-1.1.1.0/StateVar-1.1.1.0.tar.gz : 1a89cd2632c2fc384b4c71fdc12894cc1c3902badbf4771497437e4044274e80
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains state variables, which are references in the IO monad, like IORefs or parts of the OpenGL state.
description: "This package contains state variables, which are references in the IO monad, like IORefs or parts of the OpenGL state. \n"
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-stm
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
